# Generated by Django 4.0.4 on 2022-04-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('waist', models.FloatField()),
                ('hip', models.FloatField()),
                ('bust', models.FloatField()),
                ('arms', models.FloatField()),
                ('thigh', models.FloatField()),
                ('bottom', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
